function mc_bst_create_headmodel(fileName)
% mc_bst_create_headmodel: uses brainstorm scripts to compute the headmodel
%
% USAGE:    mc_bst_create_headmodel(fileName)
%
% INPUT:    fileName = study name
%
% Author: Elizabeth Bock, 2010
% --------------------------- Script History ------------------------------
% EB 2010    Creation (adapted from brainstorm3 scripts)
% EB 13/06/2012 updated for use with new brainstorm scripts
% -------------------------------------------------------------------------

[sStudy, iStudy] = bst_get('Study', fileName);
sFiles = {sStudy.Data.FileName};
 
% Process: Compute head model
sFiles = bst_process(...
    'CallProcess', 'process_headmodel', ...
    sFiles, [], ...
    'sourcespace', 1, ...
    'meg', {3, {'<none>','Single sphere', 'Overlapping spheres', 'OpenMEEG BEM'}}, ...
    'eeg', {1, {'<none>','3-shell sphere', 'OpenMEEG BEM'}}, ...
    'openmeeg', struct(...
         'BemFiles', {{}}, ...
         'BemNames', {{'Scalp', 'Skull', 'Brain'}}, ...
         'BemCond', [1, 0.0125, 1], ...
         'BemSelect', [1, 1, 1], ...
         'isAdjoint', 0, ...
         'isAdaptative', 1, ...
         'isSplit', 0, ...
         'SplitLength', 4000));

disp('Done.');
